import React from 'react';
import Head from 'next/head';
import Navbar from '../components/Header';
import MainBanner from '../components/MainBanner/Banner.jsx';
import styles from '../styles/claimToken.module.css';

import PlayCircleOutlineIcon from '@mui/icons-material/PlayCircleOutline';
import Typography from '@mui/material/Typography';
import useCD3D from '../hooks/useCD3D';
// import styles from "../styles/mainBanner.module.css";
import useAuth from '../hooks/useAuth';
import Button from '@mui/material/Button';
import { useWeb3React } from '@web3-react/core';
import ReactPlayer from 'react-player';

function ClaimToken() {
  const { getSampleToken } = useCD3D();
  const { active } = useWeb3React();
  const { login } = useAuth();
  return (
    <div className={styles.container}>
      <Head>
        <title>CD3D</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Navbar />
      <div className={styles.mainBanner}>
        <div className={styles.bannerInner}>
          <div className={styles.bannerContent}>
            <Typography variant='h4' gutterBottom component='h3'>
              Where <span>DeFi</span> and<span> Gaming</span> meet{' '}
              <div>
                <i>Play. Trade. Hold. WIN.</i>
              </div>
            </Typography>
            <Typography variant='subtitle1' gutterBottom component='p'>
              Add "0x414FA976F7E0AD63e80B93cee4CF7E6cE6Aa8704" Token Address to your metamask to claim tokens
            </Typography>
            {active ? (
              <Button variant='contained' className={styles.LikeWin} onClick={getSampleToken}>
                <Typography variant='subtitle1' className={styles.winningBtn}>
                  Get Tokens To Play
                </Typography>
              </Button>
            ) : (
              <Button variant='contained' className={styles.LikeWin} onClick={() => login('Injected')}>
                <Typography variant='subtitle1' className={styles.winningBtn}>
                  Connect Wallet To get Tokens
                </Typography>
              </Button>
            )}

            <div className={styles.bannerVideo}>
              <ReactPlayer url='https://youtu.be/ColLJVtLm6E' playIcon={<PlayCircleOutlineIcon />} />
            </div>
          </div>
          {/* </Grid> */}
        </div>
        {/* </Grid>  */}
        {/* </Container> */}
      </div>
    </div>
  );
}

export default ClaimToken;
