import React from "react";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import "devextreme/dist/css/dx.light.css";
import MainBanner from "../components/MainBanner/Banner.jsx";
import CounterSection from "../components/Countdown";
import CD3DSection from "../components/Cd3dSec";
import UseSection from "../components/UseSection";
import SoonSection from "../components/Comingsoon";
import TokeContent from "../components/TokeContent";
import DraftSection from "../components/DraftSec";
import DexSection from "../components/DexSec";
import SocialSection from "../components/SocialSec";
import MerchSection from "../components/MerchSec";
import FaqSection from "../components/FaqSec";
import SeenSection from "../components/SeenSection";
import Timeline from "../components/Timeline/Timeline";
import ErrorBoundary from "../components/ErrorBound/ErrorBound";
import PresaleBanner from "../components/presaleBanner/PresaleBanner";


export default function Home() {
  return (
    <ErrorBoundary>
      <div className={styles.container}>
        <Head>
          <title>CD3D</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no"/>
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <PresaleBanner />
        <MainBanner className={styles.mainBanner} />
        <CounterSection />
        <CD3DSection />
        <UseSection />
        <SoonSection />
        <TokeContent />
        <DraftSection />
        <Timeline />
        <DexSection />
        <SocialSection />
        <MerchSection />
        <FaqSection />
        <SeenSection />
      </div>
    </ErrorBoundary>
  );
}
